### Agent login
POST http://localhost:8000/auth/login/agent
Content-Type: application/json

{
    "organization": "MacEwan",
    "email": "badirusubomi@gmail.com",
    "password": "skjnkdjsn87y438buwie87sbdkis78dsdjun"
}

### create organization -- WORKS
POST http://localhost:8000/admin/onboard/signup/organization
Content-Type: application/json

{
  "name": "MacEwan Universities",
  "email": "macewan1@mymacewan.uni"
}


### Create admin -- WORKS
POST http://localhost:8000/admin/onboard/signup
Content-Type: application/json

{
  "email": "badirusubomi@icloud.com",
  "password": "skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "confirmPassword":"skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "firstName": "Subomi",
  "lastName": "Badiru",
  "role": "admin",
  "organizationId": "900002b6-f312-4018-9aa5-53ecfd811de9"
}


### Agent signup -- WORKS
POST http://localhost:8000/admin/team/add
Content-Type: application/json

{
  "email": "badirusubomi@gmail.com",
  "password": "skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "confirmPassword":"skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "firstName": "subomi",
  "lastName": "badiru",
  "role": "agent",
  "organizationId": "900002b6-f312-4018-9aa5-53ecfd811de9"
}