
### 1. create organization -- WORKS
POST http://localhost:8080/admin/onboard/signup/organization
Content-Type: application/json

{
  "name": "MacEwan Universities",
  "email": "macewan1@mymacewan.uni"
}


### 2. Create admin -- WORKS
POST http://localhost:8080/admin/onboard/signup
Content-Type: application/json

{
  "email": "badirusubomi@icloud.com",
  "password": "skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "confirmPassword":"skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "firstName": "Subomi",
  "lastName": "Badiru",
  "role": "admin",
  "organizationId": "508ab225-6a45-499e-8dfc-25009229ce38"
}


### 3. Agent signup -- WORKS
POST http://localhost:8080/admin/team/add
Content-Type: application/json
x-access-token: YouMayPass

{
  "email": "badirusubomi@gmail.com",
  "password": "skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "confirmPassword":"skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "firstName": "subomi",
  "lastName": "badiru",
  "role": "agent",
  "organizationId": "508ab225-6a45-499e-8dfc-25009229ce38"
}

### 3. b. Agent signup -- WORKS
POST http://localhost:8080/admin/team/add
x-access-token: YouMayPass
Content-Type: application/json

{
  "email": "badirusubomi+2@gmail.com",
  "password": "skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "confirmPassword":"skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "firstName": "subomi",
  "lastName": "badiru",
  "role": "agent"
}


### 4. Agent login -- WORKS
POST http://localhost:8080/agent/auth/login
Content-Type: application/json

{
  "email": "badirusubomi@gmail.com",
  "password": "skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "organizationName": "MacEwan Universities"
}


### 5. Admin login -- WORKS
POST http://localhost:8080/admin/auth/login
Content-Type: application/json

{
  "email": "badirusubomi@icloud.com",
  "password": "skjnkdjsn87y438buwie87sbdkis78dsdjunASWE1@",
  "organizationName": "MacEwan Universities"
}


### 6. Get Team Member 
GET http://localhost:8080/admin/team/badirusubomi+2@gmailer.com
x-access-token: YouMayPass
